blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æŸ¥çœ‹æ–‡æ¡£
    url: https://github.com/Entropy-Increase-Team/endfield-plugin#readme
    about: åœ¨æäº¤ Issue ä¹‹å‰ï¼Œè¯·å…ˆæŸ¥é˜…é¡¹ç›®æ–‡æ¡£
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/Entropy-Increase-Team/endfield-plugin/discussions
    about: å¦‚æœæœ‰ç–‘é—®æˆ–æƒ³æ³•ï¼Œæ¬¢è¿åœ¨è®¨è®ºåŒºäº¤æµ
  - name: QQç¾¤
    url: https://qm.qq.com/q/1gEjaWXf6w
    about: æ¬¢è¿è¿›ç¾¤èŠå¤©æ°´ç¾¤æˆ–è€…äº¤æµ
